#SPDX-License-Identifier: MIT-0
---
# defaults file for app_deploy
app_image_path: ""
app_image_name: ""
app_container_name: ""
app_ports:
  - ""
app_envs: {} 
app_volumes: []
app_ro_fs: false
app_cpus: null
app_memory: null