#SPDX-License-Identifier: MIT-0
---
# handlers file for ssh_hardening
- name: Restart sshd
  service: 
    name: "{{'ssh' if ansible_facts.distribution in ['Ubuntu'] else 'sshd'}}"
    state: restarted