#SPDX-License-Identifier: MIT-0
---
# tasks file for fail2ban_configuration

- name: debug
  debug: 
    msg: "{{ app_fail2ban_ports | type_debug }}"

- name: Validate port(s)
  assert:
    that: 
    - item >= 0
    - item <= 65535
    fail_msg: "Port(s) is not valid"
  loop: "{{ app_fail2ban_ports | string | split(',') | map('int') | list }}"

- name: Install fail2ban
  include_role: 
    name: fail2ban_install

- name: Create parent dirs if not exist
  ansible.builtin.file:
    path: "{{ app_log_path | dirname }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Create log file if not exists
  copy:
    content: ''
    dest: "{{ app_log_path }}"
    mode: 0644
    owner: root
    group: root
    force: no

- name: Set fail2ban regex for generic
  set_fact: 
    app_fail2ban_final_regex: '^<HOST> - - .*"(GET|POST|PUT|DELETE) .*" (401|403) .*$'
  when: app_fail2ban_filter | trim == "app-generic"

- name: Set fail2ban regex for other
  set_fact: 
    app_fail2ban_final_regex: "{{ app_fail2ban_regex }}"
  when: app_fail2ban_filter | trim != "app-generic"

- name: Create template for filter
  template: 
    src: template.conf
    dest: "/etc/fail2ban/filter.d/{{ app_fail2ban_filter }}.conf"
    mode: 0644
    owner: root
    group: root
  when: app_fail2ban_filter not in preinstalled_fail2ban_filters
  notify: Restart fail2ban

- name: Insert jail rule to jail.local
  blockinfile: 
    path: /etc/fail2ban/jail.local
    append_newline: true
    prepend_newline: true
    block: |
      [{{ app_fail2ban_filter }}]
      enabled = true
      port = {{ app_fail2ban_ports }}
      filter = {{ app_fail2ban_filter }}
      logpath = {{ app_log_path }}
      maxretry = {{ app_fail2ban_maxretry }}
      bantime = {{ app_fail2ban_bantime }}
      findtime = {{ app_fail2ban_findtime }}
  notify: Restart fail2ban
