# SPDX-License-Identifier: MIT-0
---
# tasks file for fail2ban_configuration

- name: Validate port(s)
  ansible.builtin.assert:
    that:
      - item >= 0
      - item <= 65535
    fail_msg: "Port(s) is not valid"
  loop: "{{ fail2ban_configuration_app_fail2ban_ports | string | split(',') | map('int') | list }}"

- name: Install fail2ban
  ansible.builtin.include_role:
    name: fail2ban_install

- name: Create parent dirs if not exist
  ansible.builtin.file:
    path: "{{ fail2ban_configuration_app_log_path | dirname }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create log file if not exists
  ansible.builtin.copy:
    content: ''
    dest: "{{ fail2ban_configuration_app_log_path }}"
    mode: "0644"
    owner: root
    group: root
    force: false

- name: Set fail2ban regex for generic
  ansible.builtin.set_fact:
    fail2ban_configuration_app_fail2ban_final_regex: '^<HOST> - - .*"(GET|POST|PUT|DELETE) .*" (401|403) .*$'
  when: fail2ban_configuration_app_fail2ban_filter | trim == "app-generic"

- name: Set fail2ban regex for other
  ansible.builtin.set_fact:
    fail2ban_configuration_app_fail2ban_final_regex: "{{ app_fail2ban_regex }}"
  when: fail2ban_configuration_app_fail2ban_filter | trim != "app-generic"

- name: Create template for filter
  ansible.builtin.template:
    src: template.conf
    dest: "/etc/fail2ban/filter.d/{{ fail2ban_configuration_app_fail2ban_filter }}.conf"
    mode: "0644"
    owner: root
    group: root
  when: fail2ban_configuration_app_fail2ban_filter not in fail2ban_configuration_preinstalled_fail2ban_filters
  notify: Restart fail2ban

- name: Insert jail rule to jail.local
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    append_newline: true
    prepend_newline: true
    block: |
      [{{ fail2ban_configuration_app_fail2ban_filter }}]
      enabled = true
      port = {{ fail2ban_configuration_app_fail2ban_ports }}
      filter = {{ fail2ban_configuration_app_fail2ban_filter }}
      logpath = {{ fail2ban_configuration_app_log_path }}
      maxretry = {{ fail2ban_configuration_app_fail2ban_maxretry }}
      bantime = {{ fail2ban_configuration_app_fail2ban_bantime }}
      findtime = {{ fail2ban_configuration_app_fail2ban_findtime }}
  notify: Restart fail2ban
