#SPDX-License-Identifier: MIT-0
---
# tasks file for app_deploy
- block:
  - name: Install pip and necessary libraries (RHEL-based systems)
    yum: 
      name: "{{ item }}"
      state: present
    loop:
      - python3-pip
      - python3-requests
    when: ansible_facts.os_family == "RedHat"

  - name: Install pip and necessary libraries (Debian-based systems)
    apt: 
      name: "{{ item }}"
      state: present
    loop:
      - python3-pip
      - python3-requests
    when: ansible_facts.os_family == "Debian"

  - name: Check parameters 
    assert:
      that: 
        - app_image_name != ""
        - app_image_path != ""
        - app_container_name != ""
      fail_msg: Not enough given parameters to start role 
      success_msg: Parameters are good

  - name: Copy image archive to host
    copy:
      src: "{{ app_image_path }}"
      dest: "/tmp/{{ app_container_name }}__{{ now(utc=true,fmt='%Y-%m-%d__%H:%M:%S') }}"
    register: result_copying
      
  - name: Load image archive to docker
    community.docker.docker_image_load:
      path: "{{ result_copying.dest }}"

  - name: Start container
    docker_container:
      name: "{{ app_container_name }}"
      image: "{{ app_image_name }}" 
      ports: "{{ app_ports }}"
      env: "{{ app_envs }}"
      volumes: "{{ app_volumes }}"
      read_only: "{{ app_ro_fs }}"
      cpus: "{{ app_cpus }}"
      memory: "{{ app_memory }}"

  always:
  - name: Delete image tar archive
    file: 
      path: "{{ result_copying.dest }}"
      state: absent