---
- name: Configure
  hosts: all
  become: true

  tasks:
    - name: Update repos
      ansible.builtin.include_role:
        name: update_repos

    - name: Configure ssh
      ansible.builtin.include_role:
        name: ssh_hardening

    - name: Configure fail2ban for ssh
      ansible.builtin.include_role:
        name: ssh_fail2ban_configuration
      when: ssh_fail2ban_state

    - name: Install docker
      ansible.builtin.include_role:
        name: docker_install

    - name: Configure fail2ban for docker container
      ansible.builtin.include_role:
        name: fail2ban_configuration
      when: enable_container_fail2ban

    - name: Deploy app
      ansible.builtin.include_role:
        name: app_deploy
