---
- name: Configure
  hosts: all
  become: true

  tasks:
  - name: Update repos
    include_role: 
      name: update_repos
    
  - name: Configure ssh
    include_role: 
      name: ssh_hardening
  
  - name: Configure fail2ban for ssh
    include_role:
      name: ssh_fail2ban_configuration
    when: ssh_fail2ban_state == True
  
  - name: Install docker
    include_role:
      name: docker_install

  - name: Deploy app
    include_role:
      name: app_deploy

  - name: Configure fail2ban for docker container
    include_role:
      name: fail2ban_configuration
    when: enable_container_fail2ban == True
  