---
- name: Test
  hosts: all
  become: True

  tasks:
  - name: Try
    include_role:
      name: fail2ban_configuration
    vars:
      app_ports: 80,443
      app_log_path: /var/log/apache2/access.log
      app_fail2ban_filter: custom
      app_fail2ban_maxretry: 5
      app_fail2ban_bantime: 7200
      app_fail2ban_findtime: 1800
      app_fail2ban_regex: ^<HOST> -.*"POST /login.* HTTP/[0-9\.]+" 401 .*$