# SPDX-License-Identifier: MIT-0
---
# tasks file for update_repos
- name: Update repos (RHEL-based)
  ansible.builtin.dnf:
    name: epel-release
  when: ansible_facts.os_family == "RedHat" and ansible_facts.distribution != "Fedora"
  failed_when: false

- name: Update repos (Debian-based)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts.os_family == "Debian"
