# SPDX-License-Identifier: MIT-0
# tasks file for docker_install
---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install docker on debian-based systems
  when: ansible_facts.os_family == 'Debian'
  block: # Debian based
    - name: Delete old docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_install_list_of_packages_to_delete.ubuntu if ansible_facts.distribution == 'Ubuntu' \
       else docker_install_list_of_packages_to_delete.debian }}"
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Install necessary packages
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - curl
        - ca-certificates

    - name: Create directory and change permissions
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Download gpg keys
      ansible.builtin.uri:
        url: "https://download.docker.com/linux/{{ 'ubuntu' if ansible_facts.distribution in ['Ubuntu'] else 'debian' }}/gpg"
        method: GET
        dest: /etc/apt/keyrings/docker.asc
        follow_redirects: safe
      register: docker_install_result
      failed_when: "docker_install_result.status != 200 and docker_install_result.status != 304"

    - name: Change permissions for gpg file
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: a+r
        owner: root
        group: root

    - name: Add repository for docker
      ansible.builtin.template:
        src: docker.sources.j2
        dest: /etc/apt/sources.list.d/docker.sources
        mode: "0644"
        owner: root
        group: root

    - name: Update repositories
      ansible.builtin.apt:
        update_cache: true

    - name: Install docker
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- name: Install docker on RHEL-based systems
  when: ansible_facts.os_family == "RedHat"
  block: # RHEL based
    - name: Delete old docker packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ docker_install_list_of_packages_to_delete.fedora if ansible_facts.distribution == 'Fedora' \
       else docker_install_list_of_packages_to_delete.centos if ansible_facts.distribution == 'CentOS' \
       else docker_install_list_of_packages_to_delete.rhel }}"
      when: "'docker-ce' not in ansible_facts.packages"

    - name: Install dnf-plugincs-core
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      when: "ansible_facts.distribution != 'Fedora'"

    - name: Add Docker CE repository for RHEL/CentOS
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: "https://download.docker.com/linux/{{ 'centos' if ansible_facts.distribution == 'CentOS' \
         else 'fedora' if ansible_facts.distribution == 'Fedora' else 'rhel' }}/$releasever/$basearch/stable"
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/rhel/gpg
        enabled: true

    - name: Install docker
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

- name: Start and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding ansible user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
